### ISSUE TITLE
String converting to Number when exporting

### ISSUE THREAD

**Issue by alamgir8** [zheeeng/export-from-json#149]
If a value is like this "00034", it's exporting only the number 34, when using CSV download but as it String, should export as it is like "00034",

Can you please let me know how can I omit that to convert a String into a Number?

**Comment by zheeeng** [comment]
The converted content comes from the raw data, `export-from-json` doesn't modify it. This displaying logic is of the CSV opener.
If it's you read it, you can configure it on the CSV Reader side.
Otherwise, you can add some special prefix symbol to prevent the omitting leading zero behavior. For example change the `00034` to `serial: 00034`, `s00034`, etc.
