### ISSUE TITLE
Failed to construct 'MouseEvent': Failed to read the 'view' property from 'UIEventInit': Failed to convert value to 'Window'.

### ISSUE THREAD

**Issue by q774221810** [zheeeng/export-from-json#75]
Failed to construct 'MouseEvent': Failed to read the 'view' property from 'UIEventInit': Failed to convert value to 'Window'.

**Comment by zheeeng** [comment]
Can you provide more information?

**Comment by q774221810** [comment]
@zheeeng i use it in qiankun.js. In my impression, qiankun.js has not ui event

**Comment by zheeeng** [comment]
> @zheeeng i use it in qiankun.js. In my impression, qiankun.js has not ui event

It's maybe a bug caused by qiankun.js, which is trying mock a MouseEvent.

The default processor is front-end downloader.

I you can change the downling trigger from anchor dispatch MouseEvent to call `anchor.click()` and then pass a custom processor.

https://github.com/zheeeng/export-from-json/blob/master/src/processors.ts#L70-L76

**Comment by zheeeng** [comment]
@q774221810 what's the qiankun version? seems something bug related to https://github.com/umijs/qiankun/pull/885.

**Comment by zheeeng** [comment]
Close this issue for housekeeping. If there is anything else for asking please feel free to reopen it.
